### PR TITLE
Create item

### PR DESCRIPTION
**Pull request by felberto**

### CODE REVIEW

**Comment by felberto** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 13
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/Webshop/webshop/pullRequest?prid=3435594&bid=12313259)

**Comment by felberto** [comment]
- description textfield
- short description (30 zeichen)

**Comment by felberto** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 13
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/Webshop/webshop/pullRequest?prid=3435594&bid=12313259)

**Comment by Meli-01** [comment]
Design des Upload Buttons schöner darstellen -> siehe Profile

**Comment by felberto** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 3
- Added 13
           
```


See the complete overview on [Codacy](https://app.codacy.com/app/Webshop/webshop/pullRequest?prid=3435594&bid=12313259)

**Pull request merged**
